channels:
  - conda-forge

dependencies:
  - python=3.7.3
  # https://www.anaconda.com/utilizing-the-new-compilers-in-anaconda-distribution-5/
  - c-compiler=1.0.4
  - cmake=3.14.0
  - qt=5.12.5  # conda-forge does not have 5.13.2 available
  - pip
  - pytorch=1.3.0
  - pyyaml
  - tensorboard=2.5.0
  - pandas
  - pip:
    - gym3==0.3.3
    - numpy==1.17.2
    - gym==0.15.3
    - filelock==3.0.10

# you will also need to install the custom procgen environment created by openai and then modified
# by the goal misgeneralisation paper authors and then by me
# at https://github.com/myndrws/procgenAISC/tree/master
